language: cpp
sudo: required
dist: trusty
os:
    - linux
    - windows
compiler:
    - g++
    - clang
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user cpp-coveralls; fi
after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash) -t 1cf15c36-7686-41d9-99e4-fb530dd096e5; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lcov --capture --directory . --output-file coverage.info; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lcov --remove coverage.info '/usr/*' --output-file coverage.info; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then lcov --list coverage.info; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.info || "Codecov didn't collect coverage reports"; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then coveralls --build-root .build/linux/release --gcov-options '\-lp' -e sample -e .build/linux/release/CMakeFiles -e .build/linux/release/googletest-src -e .build/linux/debug; fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - g++-7
            - gcc-7
            - clang-5.0
            - gcovr
            - lcov
            - cmake
            - cmake-data
script:
    - export CC=gcc-7
    - export CXX=g++-7
    - gcc -v && g++ -v && cmake --version
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./build --clear --linux --test --binary --debug --static; fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ./build --clear --windows --test --binary --debug --static; fi
