language: cpp
sudo: required
dist: trusty
os:
    - linux
compiler:
    - g++
    - clang
before_install:
    - sudo apt update -qq
after_success:
    - bash <(curl -s https://codecov.io/bash) -t 1cf15c36-7686-41d9-99e4-fb530dd096e5
    - lcov --capture --directory . --output-file coverage.info
    - lcov --remove coverage.info '/usr/*' --output-file coverage.info
    - lcov --list coverage.info
    - bash <(curl -s https://codecov.io/bash) -f coverage.info || "Codecov didn't collect coverage reports"
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - g++-7
            - gcc-7
            - clang-5.0
            - cmake-data
            - cmake
            - gcov
            - gcovr
            - lcov
script:
    - export CC=gcc-7
    - export CXX=g++-7
    - gcc -v && g++ -v && cmake --version
    - ./build --clear --release --debug --test
