language: cpp
sudo: required
dist: bionic
os:
    - linux
compiler:
    - g++
    - clang
before_install:
    - sudo apt update -qq
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - g++-7
            - gcc-7
            - clang-5.0
            - cmake-data
            - cmake
script:
    - ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
    - ln -s /usr/bin/g++-7 /usr/local/bin/g++
    - export CC=gcc-7
    - export CXX=g++-7
    - gcc -v && g++ -v && cmake --version
    - ./build --clear --release --debug --test
