language: cpp
sudo: required
dist: trusty
os:
    - linux
    - windows
compiler:
    - g++
    - clang
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; pip install --user cpp-coveralls fi
after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; bash <(curl -s https://codecov.io/bash) -t 1cf15c36-7686-41d9-99e4-fb530dd096e5 fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; lcov --capture --directory . --output-file coverage.info fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; lcov --remove coverage.info '/usr/*' --output-file coverage.info fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; lcov --list coverage.info fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; bash <(curl -s https://codecov.io/bash) -f coverage.info || "Codecov didn't collect coverage reports" fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; coveralls --build-root .build/release --gcov-options '\-lp' -e sample -e .build/release/CMakeFiles -e .build/release/googletest-src -e .build/debug fi
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - g++-7
            - gcc-7
            - clang-5.0
            - gcovr
            - lcov
            - cmake
            - cmake-data
script:
    - export CC=gcc-7
    - export CXX=g++-7
    - gcc -v && g++ -v && cmake --version
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; ./build --clear --linux --binary --test --debug --release --static --dynamic fi
    - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; ./build --clear --windows --binary --test --debug --release --static --dynamic fi
