#!/bin/bash

CMAKE=/usr/bin/cmake

clean() {
    echo "*****************************************"
    echo "** Removing old build                  **"
    echo "*****************************************"
    [[ -d bin ]] && rm -fr bin
    [[ -d .build ]] && rm -fr .build
}

debug() {
    echo "*****************************************"
    echo "** Building debug binaries             **"
    echo "*****************************************"
    local verbose="$1"
    local static="$2"
    local dynamic="$3"

    if [[ "$static" == 1 ]]; then
        $CMAKE -DCMAKE_BUILD_TYPE=Debug \
               -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
               -Denable-static=ON ../../..

        [[ $? -eq 0 ]] || exit 1
        [[ "$verbose" == 1 ]] && VERBOSE=1 make -j$(nproc) || make -j$(nproc)
    fi

    if [[ "$dynamic" == 1 ]]; then
        $CMAKE -DCMAKE_BUILD_TYPE=Debug \
               -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
               -Denable-static=OFF ../../..

        [[ $? -eq 0 ]] || exit 1
        [[ "$verbose" == 1 ]] && VERBOSE=1 make -j$(nproc) || make -j$(nproc)
    fi
}

release() {
    echo "*****************************************"
    echo "** Building release binaries           **"
    echo "*****************************************"
    local verbose="$1"
    local static="$2"
    local dynamic="$3"

    if [[ "$static" == 1 ]]; then
        $CMAKE -DCMAKE_BUILD_TYPE=Release \
               -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
               -Denable-static=ON ../../..

        [[ $? -eq 0 ]] || exit 1
        [[ "$verbose" == 1 ]] && VERBOSE=1 make -j$(nproc) || \
                                           make -j$(nproc)
    fi

    if [[ "$dynamic" == 1 ]]; then
        $CMAKE -DCMAKE_BUILD_TYPE=Release \
               -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
               -Denable-static=OFF ../../..

        [[ $? -eq 0 ]] || exit 1
        [[ "$verbose" == 1 ]] && VERBOSE=1 make -j$(nproc) || \
                                           make -j$(nproc)
    fi
}

coverage() {
    echo "*****************************************"
    echo "** Running test cases                  **"
    echo "*****************************************"
    local static="$1"
    local dynamic="$2"
    local debug="$3"
    local verbose="$4"

    [[ -d googletest-build ]] || update="ON"
    [[ -d googletest-src ]] || update="ON"

    if [[ "$debug" == 0 ]]; then
        $CMAKE -DCMAKE_BUILD_TYPE=Release \
               -Denable-test=ON \
               -Denable-static="$static" \
               -Dupdate-gtest="$update" ../../..
    fi

    if [[ $debug == 1 ]]; then
        $CMAKE -DCMAKE_BUILD_TYPE=Debug \
               -Denable-test=ON \
               -Denable-static="$static" \
               -Dupdate-gtest="$update" ../../..
    fi

    [[ $? -eq 0 ]] || exit 1
    [[ "$verbose" == 1 ]] && VERBOSE=1 make coverage || \
        make coverage
}

usage() {
    local error="$1"
    local program="$2"
    local option="$3"

    [[ "$error" == 1 ]] && echo "option $option not recognized"
    cat <<-EOF
        Usage: $program [options]

            --clear         delete build artifacts
            --binary        build binaries
            --test          build (and run) test with coverage
            --debug         debug symbols on
            --release       optimizations on
            --static        static library
            --dynamic       dynamic library
            --linux         for Linux
            --windows       for Windows
            --update        update googletest
            --verbose       build verbose mode
            --help          print this help and exit
EOF
    exit 1
}

just_make() {
    echo "*****************************************"
    echo "** Make                                **"
    echo "*****************************************"
    if [[ -d .build/release ]]; then
        cd .build/release
        make -j$(nproc)
        cp -a bin/* ../../bin/release
        cd ../..
    fi

    if [[ -d .build/debug ]]; then
        cd .build/debug
        make -j$(nproc)
        cp -a bin/* ../../bin/debug
        cd ../..
    fi
}

build_binary() {
    local static="$1"
    local dynamic="$2"
    local debug="$3"
    local verbose="$4"

    [[ "$debug" == 1 ]] && debug "$verbose" "$static" "$dynamic" \
                        || release "$verbose" "$static" "$dynamic"
}

build_test() {
    local static="$1"
    local dynamic="$2"
    local debug="$3"
    local verbose="$4"

    coverage "$static" "$release" "$debug" "$update" "$windows"
}

main() {
    local test=0
    local clear=0
    local debug=0
    local release=0
    local windows=0
    local linux=0
    local verbose=0
    local binary=0
    local static=0
    local dynamic=0
    local update="OFF"

    if [[ -z "$1" ]]; then
        just_make
        exit 0
    fi

    while [[ "$1" == --* ]]; do
        local opt="$1"
        shift

        case "$opt" in
            --test)
                test=1
                ;;
            --binary)
                binary=1
                ;;
            --clear)
                clear=1
                ;;
            --debug)
                debug=1
                ;;
            --release)
                release=1
                ;;
            --static)
                static=1
                ;;
            --dynamic)
                dynamic=1
                ;;
            --linux)
                linux=1
                ;;
            --windows)
                windows=1
                ;;
            --update)
                update="ON"
                ;;
            --verbose)
                verbose=1
                ;;
            --help)
                usage 0 "$0" ""
                ;;
            *)
                usage 1 "$0" "$opt"
                ;;
        esac
    done

    [[ "$clear" == 1 ]] && clean

    if [[ "$windows" == 1 ]]; then
        export CC=/usr/bin/i686-w64-mingw32-gcc
        export CXX=/usr/bin/i686-w64-mingw32-g++
        #CMAKE=/usr/bin/mingw32-cmake
        CMAKE=/usr/bin/cmake

        if [[ "$binary" == 1 ]]; then
            mkdir -p bin/windows
            mkdir -p .build/windows
            cd .build/windows

            if [[ "$release" == 1 ]]; then
                mkdir -p ../../bin/windows/release
                mkdir -p release
                cd release
                build_binary "$static" "$dynamic" 0 "$verbose"
                cd ..
                cp -a release/bin/* ../../bin/windows/release
            fi

            if [[ "$debug" == 1 ]]; then
                mkdir -p ../../bin/windows/debug
                mkdir -p debug
                cd debug
                build_binary "$static" "$dynamic" 1 "$verbose"
                cd ..
                cp -a debug/bin/* ../../bin/windows/debug
            fi
            cd ../..
        fi

        if [[ "$test" == 1 ]]; then
            mkdir -p .build/windows
            cd .build/windows

            if [[ "$release" == 1 ]]; then
                mkdir -p ../../bin/windows/release
                mkdir -p release
                cd release
                build_test "$static" "$dynamic" 0 "$update"
                cd ..
                cp -a release/bin/* ../../bin/windows/release
            fi

            if [[ "$debug" == 1 ]]; then
                mkdir -p ../../bin/windows/debug
                mkdir -p debug
                cd debug
                build_test "$static" "$dynamic" 1 "$update"
                cd ..
                cp -a debug/bin/* ../../bin/windows/debug
            fi
            cd ../..
        fi
    fi

    if [[ "$linux" == 1 ]]; then
        export CC=/usr/bin/gcc
        export CXX=/usr/bin/g++
        CMAKE=/usr/bin/cmake

        if [[ "$binary" == 1 ]]; then
            mkdir -p bin/linux
            mkdir -p .build/linux
            cd .build/linux

            if [[ "$release" == 1 ]]; then
                mkdir -p ../../bin/linux/release
                mkdir -p release
                cd release
                build_binary "$static" "$dynamic" 0 "$verbose"
                cd ..
                cp -a release/bin/* ../../bin/linux/release
            fi

            if [[ "$debug" == 1 ]]; then
                mkdir -p ../../bin/linux/debug
                mkdir -p debug
                cd debug
                build_binary "$static" "$dynamic" 1 "$verbose"
                cd ..
                cp -a debug/bin/* ../../bin/linux/debug
            fi
            cd ../..
        fi

        if [[ "$test" == 1 ]]; then
            mkdir -p bin/linux
            mkdir -p .build/linux
            cd .build/linux

            if [[ "$release" == 1 ]]; then
                mkdir -p ../../bin/linux/release
                mkdir -p release
                cd release
                build_test "$static" "$dynamic" 0 "$update"
                cd ..
                cp -a release/bin/* ../../bin/linux/release
            fi

            if [[ "$debug" == 1 ]]; then
                mkdir -p ../../bin/linux/debug
                mkdir -p debug
                cd debug
                build_test "$static" "$dynamic" 1 "$update"
                cd ..
                cp -a debug/bin/* ../../bin/linux/debug
            fi
            cd ../..
        fi
    fi
}

main $@
